### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by ASKabalan** [ASKabalan/Definitly-not-vscode#1]
List of things to do

- [x] Add a setup shell file to install the whole thing
- [ ] Add a Nerdfont installation tutorial
- [ ] Add Debugging for python and C++ tutorial
- [ ] Make Bazel work and add it to markdown
